#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AudioTour.Resource", IsApplication=true)]

namespace AudioTour
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int nextbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pausebutton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int playbutton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int previousbutton = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int ButtonAddNewUser = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ButtonMain = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int btnPlay = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int btnStop = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int gridLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int imageButton1 = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int relativeLayout1 = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int seekBar1 = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int space1 = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int space2 = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int txtEmail = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int txtName = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int txtOut = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewUserScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TourScreen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int controlla = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ButtonAddNewUser = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ButtonMain = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int NewUserEmail = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int NewUserName = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int NewUserScreenTitle = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
